@startuml
title Гидрографическая сеть Республики Бенин


package "Северный бассейн (бассейн р. Нигер)" {
    [р. Мекру]
    [р. Алибори]
    [р. Сота]
    [р. Нигер] as Niger
    Niger <-- [р. Мекру]
    Niger <-- [р. Алибори]
    Niger <-- [р. Сота]
}

package "Южный бассейн (бассейн Гвинейского залива)" {
    [р. Уэме] as Oueme
    [р. Зу]
	[р. Окпара]
    [р. Моно] as Mono
    [р. Куффо] as Kouffo
	
    
    Oueme <-- [р. Зу]
    Oueme <-- [р. Окпара]
    
    package "Лагунная система" {
		[Гвинейский залив]
        [оз. Нокуэ] as Nokoue
        [лагуна Порто-Ново] as PN
        [лагуна Котону] as Cotonou
        Oueme --> Nokoue
        Nokoue <-> PN
        Nokoue <-> Cotonou

		Cotonou --> [Гвинейский залив]
		Mono --> [Гвинейский залив]
		Kouffo --> [Гвинейский залив] 
    }
}
   

@enduml
